project_name: cascadiad

env:
  - CGO_ENABLED=1
  - COSMWASM_VERSION=1.2.3

builds:
  - id: cascadiad-darwin-amd64
    main: ./cmd/cascadiad/main.go
    binary: cascadiad
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/v{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=cascadia
      - -X github.com/cosmos/cosmos-sdk/version.AppName=cascadiad
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm

  - id: cascadiad-darwin-arm64
    main: ./cmd/cascadiad/main.go
    binary: cascadiad
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/v{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=cascadia
      - -X github.com/cosmos/cosmos-sdk/version.AppName=cascadiad
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - ledger
      - static_wasm

  - id: cascadiad-linux-amd64
    main: ./cmd/cascadiad
    binary: cascadiad
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/v{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=cascadia
      - -X github.com/cosmos/cosmos-sdk/version.AppName=cascadiad
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc

  - id: cascadiad-linux-arm64
    main: ./cmd/cascadiad
    binary: cascadiad
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/v{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=cascadia 
      - -X github.com/cosmos/cosmos-sdk/version.AppName=cascadiad 
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} 
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,muslc
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - ledger
      - muslc

universal_binaries:
  - id: cascadiad-darwin-universal
    ids:
      - cascadiad-darwin-amd64
      - cascadiad-darwin-arm64
    replace: true
    name_template: "{{.ProjectName}}"

archives:
  - id: zipped
    builds:
      - cascadiad-darwin-universal
      - cascadiad-linux-amd64
      - cascadiad-linux-arm64
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - none*
  - id: binaries
    builds:
      - cascadiad-darwin-universal
      - cascadiad-linux-amd64
      - cascadiad-linux-arm64
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256